title: Gihak111
email: yeonjm12@gmail.com
description: Write an awesome description for your new site here.
baseurl: "" # 예시로 /blog, 실제 레포지토리 이름으로 대체
url: "https://github.com/Gihak111/Gihak111.github.io" # GitHub Pages URL

twitter_username: jekyllrb
github_username: jekyll
name: coding diary

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-search
  - generate_search_json

jekyll_search:
  enabled: true
  index: search.json

paginate: 5
paginate_path: "/page:num/"

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
